server:
  port: 9090

spring:
  application:
    name: brewery-gateway-service
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: lb://BEER-SERVICE
          predicates:
            - Path=/api/v1/beers/**
        - id: beer-order-service
          uri: lb://beer-order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: beer-inventory-service
          uri: lb://beer-inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        - id: INVENTORY-FAILOVER
          uri: lb://INVENTORY-FAILOVER
          predicates:
            - Path=/api/v1/inventory-failover
      discovery:
        locator:
          enabled: true

  zipkin:
    base-url: http://localhost:9411
logging:
  level:
    org.springframework: debug
eureka:
  client:
    register-with-eureka: false
