server:
  port: 9090

spring:
  application:
    name: brewery-gateway-service

  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/beers
            - Path=/api/v1/beers/*
        - id: beer-order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/
            - Path=/api/v1/orders/*
        - id: beer-inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventory
            - Path=/api/v1/inventory/*

